// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TodoApi.Models;

namespace TodoApi.Migrations
{
    [DbContext(typeof(TodoContext))]
    partial class TodoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TodoApi.Models.Event", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("OrganizationID");

                    b.Property<DateTime>("_fin");

                    b.Property<DateTime>("_inicio");

                    b.Property<string>("description");

                    b.Property<string>("img");

                    b.Property<string>("nombre");

                    b.Property<int>("organizacionID");

                    b.HasKey("ID");

                    b.HasIndex("OrganizationID");

                    b.ToTable("EventItems");
                });

            modelBuilder.Entity("TodoApi.Models.Organization", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("img");

                    b.Property<string>("mail")
                        .IsRequired();

                    b.Property<string>("nombre")
                        .IsRequired();

                    b.Property<string>("password")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("OrganizationItems");
                });

            modelBuilder.Entity("TodoApi.Models.TodoItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsComplete");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("TodoApi.Models.Event", b =>
                {
                    b.HasOne("TodoApi.Models.Organization")
                        .WithMany("eventos")
                        .HasForeignKey("OrganizationID");
                });
#pragma warning restore 612, 618
        }
    }
}
